version: 0.2

phases:
  install:
    commands:
      - echo Entered the install phase...
      #- apt-get update -y
      #- apt-get install -y maven
      
      # Upgrade AWS CLI to the latest version
      #- pip install --upgrade pip
      #- pip install --upgrade awscli
      - pip install --upgrade aws-sam-cli
  pre_build:
    commands:
      # Discover and run unit tests in the 'tests' directory
     
  build:
    commands:
      - mvn package
      # Use AWS SAM to package the application by using AWS CloudFormation
      - sam package --s3-bucket codepipeline-us-west-2-940504386797 --output-template-file packaged-template.yaml --template-file template.yaml
     # - sam package --s3-bucket codepipeline-us-west-2-940504386797 --output-template-file packaged-qa-template.yaml --template-file template-qa.yaml
artifacts:
  type: zip
  files:
    - packaged-template.yaml
  #  - packaged-qa-template.yaml
    
    
    
